# Generated by Django 4.1.1 on 2022-09-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
