# Generated by Django 4.1.1 on 2022-09-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="url",),
        migrations.AlterField(
            model_name="blog", name="description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blog", name="title", field=models.CharField(max_length=200),
        ),
    ]
